linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam

  goimports:
    local-prefixes: github.com/evert/google-workspace-mcp-go

  misspell:
    locale: US

issues:
  exclude-rules:
    # Allow unused parameters in test files
    - path: _test\.go
      linters:
        - unused

run:
  timeout: 5m
  go: "1.24"
